import Head from 'next/head';
import styled from 'styled-components';
import useSWR from 'swr';
import Card from '../components/Card';

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;
`;

const CointainerGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
`;

const fetcher = (url) => fetch(url).then((res) => res.json());

const Home = () => {
  const { data, error } = useSWR(
    'https://api.coincap.io/v2/assets?limit=20',
    fetcher
  );
  if (error) return 'An error has occurred.';
  if (!data) return 'Loading...';

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>Crypto stats</Title>
        <CointainerGrid>
          {data.data.map((el) => (
            <Card key={el.id} {...el} />
          ))}
        </CointainerGrid>
      </Main>
    </div>
  );
};

export default Home;
